config/routes.rb
Rails.application.routes.draw do
  resources :profiles, except: :show
end

app/models/enrollment_form.rb
class EnrollmentForm
  include ActiveModel::Model

  attr_accessor :email,
                :bio,
                :communication_style,
                :first_name,
                :hire_type_id,
                :last_name,
                :manager_id,
                :mentor_id,
                :photo_file_name,
                :reset_photo,
                :slack_handle,
                :team_id,
                :title

  attr_reader :profile,
              :user

  validates :email, presence: true
  validates :first_name, presence: true
  validates :hire_type_id, presence: true
  validates :last_name, presence: true
  validates :team_id, presence: true

  def formatted_name
    "#{first_name} #{last_name}"
  end

  def name
    if formatted_name.blank?
      'New Employee'
    else
      formatted_name
    end
  end

  def photo
    if photo_file_name.blank?
      default_photo
    else
      photo_file_name
    end
  end

  def reset_default_photo(profile_id)
    profile = Profile.find(profile_id)
    if reset_photo?
      profile.photo.clear
      profile.save
    end
  end

  def save
    if valid? && email_is_unique
      create_user_profile
    end
  end

  def update(user_id, profile_id)
    if email_is_unique(user_id) && valid?
      reset_default_photo(profile_id)
      update_user_profile(user_id, profile_id)
      profile = Profile.find(profile_id)
    end
  end

  private

  def create_user_profile
    new_user = User.create!(email: email)
    profile = Profile.create!(profile_attrs.merge(user: new_user))
  end

  def default_photo
    'medium/missing.png'
  end

  def email_is_unique(user_id = nil)
    if User.where(email: email).where.not(id: user_id).present?
      errors.add(:email, 'is already in use')
      false
    else
      true
    end
  end

  def profile_attrs
    { bio: bio,
      communication_style: communication_style,
      first_name: first_name,
      hire_type_id: hire_type_id,
      last_name: last_name,
      manager_id: manager_id,
      mentor_id: mentor_id,
      photo_file_name: photo_file_name,
      slack_handle: slack_handle,
      team_id: team_id,
      title: title
    }
  end

  def reset_photo?
    mapping = { '1' => true, '0' => false }
    mapping[reset_photo]
  end

  def update_user_profile(user_id, profile_id)
    user = User.find(user_id)
    user.update(email: email)
    profile = Profile.find(profile_id)
    profile.update(profile_attrs)
  end
end

app/models/hire_type.rb
class HireType < ActiveRecord::Base
  enum contract_type: [:full_time, :apprentice]
  enum work_status: [:no_visa, :visa]

  has_many :profiles

  validates_presence_of :contract_type
  validates_uniqueness_of :name
  validates_presence_of :name
  validates_presence_of :work_status

  def self.ordered
    order(:name)
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :user, dependent: :destroy
  delegate :email, to: :user
  belongs_to :hire_type
  belongs_to :team, touch: true
  belongs_to :manager, class_name: 'Profile'
  belongs_to :mentor, class_name: 'Profile'

  has_attached_file :photo, styles: { large: ['100x100#', :png],
                                      medium: ['74x74#', :png],
                                      small: ['48x48#', :png]
                                    },
                            default_url: ':style/missing.png'

  validates :bio, length: { maximum: 140 }
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :hire_type
  validates :slack_handle, length: { maximum: 21 }
  validates_presence_of :team

  validates_attachment :photo, content_type: { content_type: /\Aimage\/.*\Z/ },
                               size: { less_than: 4.megabyte }

  def self.ordered
    order(:first_name)
  end

  def photo_url(style = :large)
    photo && photo.url(style, false)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :profiles

  validates_presence_of :name

  def self.ordered
    order('lower(name)')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :profile
  validates :email, presence: true, uniqueness: true, email: true
  enum role: [:employee, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.ordered
  end

  def new
    @enrollment = EnrollmentForm.new(bio: t('helpers.defaults.profile.bio'))
  end

  def create
    @enrollment = EnrollmentForm.new(enrollment_params)

    if @enrollment.save
      flash[:notice] = t('flashes.profiles.create.success')
      redirect_to profiles_path
    else
      flash[:alert] = t('flashes.profiles.create.failure')
      render :new
    end
  end

  def edit
    @profile = find_profile
    profile_attrs = create_profile_attrs(@profile)

    @enrollment = EnrollmentForm.new(profile_attrs)
  end

  def update
    @profile = find_profile
    @enrollment = EnrollmentForm.new(enrollment_params)

    if @enrollment.update(@profile.user.id, @profile.id)
      flash[:notice] = t('flashes.profiles.update.success')
      redirect_to profiles_path
    else
      flash[:alert] = t('flashes.profiles.update.failure')
      render :edit
    end
  end

  def destroy
    @profile = Profile.find(params[:id])

    if @profile.destroy
      flash[:notice] = t('flashes.profiles.destroy.success')
      redirect_to profiles_path
    else
      flash[:alert] = t('flashes.profiles.destroy.failure')
      render :edit
    end
  end

  private

  def create_profile_attrs(profile)
    profile.
      attributes.
      except('id',
             'created_at',
             'updated_at',
             'photo_content_type',
             'photo_file_size',
             'photo_updated_at').
      merge('email' => profile.email)
  end

  def enrollment_params
    params.
      require(:enrollment_form).
      permit(:bio,
             :communication_style,
             :first_name,
             :hire_type_id,
             :last_name,
             :manager_id,
             :mentor_id,
             :photo_file_name,
             :reset_photo,
             :slack_handle,
             :team_id,
             :title,
             :email)
  end

  def find_profile
    Profile.
      includes(:user).
      find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_time_employees_for_select
    full_time_ids = HireType.full_time.pluck(:id)
    employees = Profile.where(hire_type_id: full_time_ids).order(:first_name)
    decorated_employees = ProfileDecorator.decorate_collection(employees)
    decorated_employees.map { |employee| [employee.full_name, employee.id] }
  end

  def hire_types_for_select
    HireType.ordered.map { |hire_type| [hire_type.name, hire_type.id] }
  end

  def teams_for_select
    Team.ordered.map { |team| [team.name, team.id] }
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
  def link_to_delete_profile(profile)
    link_to 'Delete User',
            profile_path(profile),
            method: :delete,
            data: { confirm: t('helpers.confirmation.delete') }
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_sidebar.html.erb
<nav class="sidebar">
  <%= link_to profiles_path do %>
    <%= image_tag('large/missing.png') %>
  <% end %>
  <ul>
    <li>
      <%= link_to 'Users', profiles_path, class: 'main-section' %>
      <ul class="sub-nav">
        <li><%= link_to 'Apprentices', profiles_path(anchor: 'apprentices') %></li>
        <li><%= link_to 'New Hires', profiles_path(anchor: 'new-hires') %></li>
        <li><%= link_to 'Employees', profiles_path(anchor: 'full-time') %></li>
      </ul>
    </li>
  </ul>
</nav>

app/views/application/_typekit.html.erb
<script src="//use.typekit.net/yye6ylr.js"></script>
<script>try{Typekit.load();}catch(e){}</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <div class="content">
    <%= render 'sidebar' -%>
    <main>
      <%= render 'flashes' -%>
      <%= yield %>
    </main>
  </div>
  <%= render 'javascript' -%>
</body>
</html>

app/views/profiles/_form_errors.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <p><%= pluralize(object.errors.count, 'error') %> prohibited this user from being submitted:</p>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<%= link_to edit_profile_path(profile), class: 'profile' do %>
  <%= image_tag(profile.photo_url(:small)) %>
  <span><%= profile.first_name %> <%= profile.last_name %></span>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form_errors.html.erb', object: @enrollment %>
<div class='profile-page'>
  <div class='profile-name'>
    <%= image_tag(@profile.photo_url(:medium)) %><h3 class='employee-name'><%= @enrollment.name %></h3>
  </div>
  <hr>
  <div class='profile-wrapper'>
    <%= simple_form_for @enrollment, url: profile_path(@profile), method: :patch do |form| %>
      <%= form.input :reset_photo, as: :boolean, label: 'Reset Profile Photo' %>
      <%= form.input :email, error: false %>
      <%= form.input :first_name, error: false %>
      <%= form.input :last_name, label: false, error: false %>
      <%= form.input :slack_handle %>
      <%= form.input :communication_style %>
      <%= form.input :hire_type_id do %>
        <%= form.select :hire_type_id, hire_types_for_select %>
      <% end %>
      <%= form.input :team_id do %>
        <%= form.select :team_id, teams_for_select %>
      <% end %>
      <%= form.input :title %>
      <%= form.input :bio do %>
        <%= form.text_area :bio, id: 'bio' %>
        <p class="js-char-count"></p>
      <% end %>
      <%= form.input :manager_id do %>
        <%= form.select :manager_id, full_time_employees_for_select, include_blank: 'None' %>
      <% end %>
      <%= form.input :mentor_id do %>
        <%= form.select :mentor_id, full_time_employees_for_select, include_blank: 'None' %>
      <% end %>
      <%= form.button :submit, 'Save' %>
      <%= link_to_delete_profile(@profile) %>
    <% end %>
  </div>
</div>

app/views/profiles/index.html.erb
<section class="profiles">
  <div id="full-time" class="profile-group">
  <h2>Full Time</h2><%= link_to '+ Add New', new_profile_path, class: 'new-profile' %>
  <% ProfileDecorator.decorate_collection(@profiles).each do |profile| %>
    <%= render 'profiles/profile', profile: profile %>
  <% end %>
</div>
</section>

app/views/profiles/new.html.erb
<%= render 'form_errors.html.erb', object: @enrollment  %>

<div class='profile-name'>
  <%= image_tag(@enrollment.photo) %><h3 class='employee-name'><span class="js-employee-name"><%= @enrollment.name %></span></h3>
</div>
<hr>
<%= simple_form_for @enrollment, url: profiles_path do |form| %>
  <%= form.input :email, error: false %>
  <%= form.input :first_name, error: false %>
  <%= form.input :last_name, label: false, error: false %>
  <%= form.input :hire_type_id do %>
    <%= form.select :hire_type_id, hire_types_for_select %>
  <% end %>
  <%= form.input :team_id do %>
    <%= form.select :team_id, teams_for_select %>
  <% end %>
  <%= form.input :title %>
  <%= form.input :bio do %>
    <%= form.text_area :bio, id: 'bio' %>
    <p class="js-char-count"></p>
  <% end %>
  <%= form.input :manager_id do %>
    <%= form.select :manager_id, full_time_employees_for_select, include_blank: 'None' %>
  <% end %>
  <%= form.input :mentor_id do %>
    <%= form.select :mentor_id, full_time_employees_for_select, include_blank: 'None' %>
  <% end %>
  <%= form.button :submit, 'Save' %>
<% end %>